### ISSUE TITLE
Samsung g8 shows black screen

### ISSUE THREAD

**Issue by TheBricktop** [justinjoy/native-camera2#3]
The camera permissions are on but screen is still black
system ver 9.0 latest

**Comment by justinjoy** [comment]
Have you checked application permission in settings?

**Comment by TheBricktop** [comment]
Yes they are given and set to on in application settings.

**Comment by TheBricktop** [comment]
Weird, scratch that, it started working

**Comment by justinjoy** [comment]
This project may need to have nicer granting permission logic, but personally, I'd like to just focus on ndk and camera :)
